export type ServiceItem = {
  n: string;
  name: string;
  nameEn?: string;
  subtitle: string;
  subtitleEn?: string;
  description: string;
  descriptionEn?: string;
  price: string;
  amount: number;
  items: readonly string[];
  searchTerms: readonly string[];
};

export const serviceGroups: readonly { title: string; titleEn?: string; packages: readonly ServiceItem[] }[] = [
  { title: "Названия", titleEn: "Naming", packages: [
    { n: "01", name: "Название, 2 варианта", nameEn: "Name — 2 options", subtitle: "Для компании, услуги, продукта или проекта", subtitleEn: "For a company, service, product or project", description: "Создаём два продуманных названия, объясняем логику каждого и предварительно проверяем совпадения.", descriptionEn: "Two considered naming options with rationale and a preliminary online similarity check.", price: "2 000 ₽", amount: 2000, items: ["2 продуманных варианта", "Краткое объяснение каждого", "Предварительный поиск совпадений в интернете"], searchTerms: ["название", "назвать", "имя", "нейминг", "компания", "продукт", "проект", "кафе", "магазин", "бренд"] },
    { n: "02", name: "Название, 5 вариантов", nameEn: "Name — 5 options", subtitle: "Для глубокого поиска и сравнения направлений", subtitleEn: "For deeper exploration and comparison", description: "Разрабатываем пять разных вариантов названия с обоснованием идей и предварительной проверкой совпадений.", descriptionEn: "Five distinct naming directions with rationale and a preliminary similarity check.", price: "5 000 ₽", amount: 5000, items: ["5 разных вариантов", "Обоснование идей", "Предварительный поиск совпадений"], searchTerms: ["много названий", "варианты названия", "пять названий", "выбрать имя", "нейминг"] },
    { n: "03", name: "Название + слоган + логотип", nameEn: "Name + slogan + logo", subtitle: "Готовая основа бренда в единой концепции", subtitleEn: "A coherent foundation for a new brand", description: "Объединяем название, слоган и три варианта простого логотипа в одну согласованную основу бренда.", descriptionEn: "Naming, slogan development and three simple logo directions combined into one brand foundation.", price: "10 000 ₽", amount: 10000, items: ["Название и слоган", "3 варианта простого логотипа", "Доработка выбранного варианта"], searchTerms: ["бренд под ключ", "название слоган логотип", "основа бренда", "все сразу", "комплекс"] },
  ]},
  { title: "Названия и слоганы", titleEn: "Naming & slogans", packages: [
    { n: "04", name: "5 вариантов слогана", nameEn: "5 slogan options", subtitle: "Короткие фразы для бренда, рекламы или продукта", subtitleEn: "Short lines for a brand, ad or product", description: "Формулируем пять коротких слоганов, которые передают смысл и обещание бренда.", descriptionEn: "Five concise slogans that communicate the brand’s meaning and promise.", price: "2 000 ₽", amount: 2000, items: [], searchTerms: ["слоган", "девиз", "фраза", "лозунг", "подпись", "обещание"] },
    { n: "05", name: "Название позиции меню (минимум 2)", nameEn: "Menu item naming — minimum 2", subtitle: "Стоимость указана за одну позицию", subtitleEn: "Price shown per item", description: "Придумываем названия для отдельных блюд или напитков с учётом концепции заведения.", descriptionEn: "Names for individual dishes or drinks based on the venue concept.", price: "1 000 ₽ / позиция", amount: 2000, items: [], searchTerms: ["название блюда", "название напитка", "позиция меню", "меню", "еда"] },
    { n: "06", name: "10 названий для меню", nameEn: "10 names for a menu", subtitle: "Единая стилистика для напитков или блюд", subtitleEn: "One consistent style for dishes or drinks", description: "Создаём десять связанных названий для цельного и запоминающегося раздела меню.", descriptionEn: "Ten connected names for a cohesive and memorable menu section.", price: "7 000 ₽", amount: 7000, items: [], searchTerms: ["10 названий меню", "десять блюд", "названия напитков", "меню"] },
    { n: "07", name: "20 названий для меню", nameEn: "20 names for a menu", subtitle: "Расширенная проработка раздела меню", subtitleEn: "Extended naming for a larger menu", description: "Создаём двадцать названий в единой стилистике для большого меню или отдельной линейки.", descriptionEn: "Twenty names in one style for a large menu or product line.", price: "12 000 ₽", amount: 12000, items: [], searchTerms: ["20 названий меню", "двадцать блюд", "большое меню", "меню"] },
  ]},
  { title: "Логотипы", titleEn: "Logos", packages: [
    { n: "08", name: "Простой логотип", nameEn: "Simple logo", subtitle: "3 варианта и доработка выбранного", subtitleEn: "3 options + refinement", description: "Разрабатываем три варианта логотипа и передаём выбранный в JPG, PNG и на прозрачном фоне.", descriptionEn: "Three logo options with the selected version delivered in JPG, PNG and transparent formats.", price: "4 000 ₽", amount: 4000, items: [], searchTerms: ["логотип", "лого", "знак", "эмблема", "символ", "иконка"] },
    { n: "09", name: "Расширенный логотип", nameEn: "Extended logo package", subtitle: "5 вариантов и полный набор версий", subtitleEn: "5 options and a complete version set", description: "Создаём пять вариантов, цветную и чёрно-белую версии, аватар и файлы для разных носителей.", descriptionEn: "Five directions, color and monochrome versions, an avatar and files for different use cases.", price: "7 500 ₽", amount: 7500, items: [], searchTerms: ["расширенный логотип", "много логотипов", "аватар", "фирменный знак", "логотип"] },
  ]},
  { title: "Реклама и креативы", titleEn: "Advertising & creatives", packages: [
    { n: "10", name: "Рекламный текст", nameEn: "Advertising copy", subtitle: "Заголовок, основной текст и призыв к действию", subtitleEn: "Headline, body copy and call to action", description: "Пишем готовый рекламный текст с понятной структурой и сильным призывом к действию.", descriptionEn: "Ready-to-use advertising copy with a clear structure and strong call to action.", price: "2 500 ₽", amount: 2500, items: [], searchTerms: ["рекламный текст", "текст объявления", "копирайтинг", "заголовок", "призыв"] },
    { n: "11", name: "Полное оформление объявления", nameEn: "Complete ad copy package", subtitle: "Структура, описание, преимущества и призыв", subtitleEn: "Structure, description, benefits and CTA", description: "Собираем все текстовые элементы объявления в единую продающую подачу.", descriptionEn: "All text elements assembled into one clear, conversion-focused advertising message.", price: "5 000 ₽", amount: 5000, items: [], searchTerms: ["объявление", "оформить рекламу", "текст рекламы", "описание", "продвижение"] },
    { n: "12", name: "1 статичный рекламный креатив", nameEn: "1 static advertising creative", subtitle: "Готовое изображение с текстом под выбранную площадку", subtitleEn: "Ready-to-use visual for the selected platform", description: "Создаём один готовый рекламный макет для социальной сети, сайта, баннера или другой площадки.", descriptionEn: "One finished advertising visual for social media, a website banner or another digital placement.", price: "1 500 ₽", amount: 1500, items: [], searchTerms: ["фото для рекламы", "фотография для рекламы", "картинка", "креатив", "баннер", "пост", "сторис", "макет", "соцсеть", "telegram", "телеграм", "meta"] },
    { n: "13", name: "5 статичных креативов", nameEn: "5 static creatives", subtitle: "Разные визуальные подачи для тестирования", subtitleEn: "Different visual directions for testing", description: "Готовим пять рекламных креативов, чтобы сравнить разные идеи и визуальные направления.", descriptionEn: "Five advertising creatives for comparing several ideas and visual approaches.", price: "6 000 ₽", amount: 6000, items: [], searchTerms: ["5 креативов", "пять картинок", "несколько баннеров", "тест рекламы", "креативы"] },
    { n: "14", name: "10 статичных креативов", nameEn: "10 static creatives", subtitle: "Полный набор вариантов для рекламной кампании", subtitleEn: "A complete set for an advertising campaign", description: "Создаём десять согласованных рекламных креативов для полноценного запуска кампании.", descriptionEn: "Ten coordinated advertising creatives for a full campaign launch.", price: "10 000 ₽", amount: 10000, items: [], searchTerms: ["10 креативов", "десять картинок", "рекламная кампания", "набор баннеров", "много креативов"] },
  ]},
];

export const serviceCatalog = serviceGroups.flatMap((group) => group.packages);
export const money = (value: number) => value.toLocaleString("ru-RU") + " ₽";
